[package]
name = "bevy-audio-dsp"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
eframe = "0.28.1"
env_logger = "0.11.3"
anyhow = "1.0"
rtrb = "0.3"
rustc-hash = "2.0"
arrayvec = "0.7.4"
basedrop = "0.1.2"
