[package]
name = "bevy-audio-dsp"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "examples/beep_test",
]

[dependencies]
ahash = "0.8.11"
log = "0.4.22"
rtrb = "0.3.1"
smallvec = "1.13.2"
thunderdome = "0.6.1"
